[package]
name = "msnchat-bindings"
version = "0.1.3"
edition = "2024"

[dependencies]
windows-core = "0.61"

[dependencies.windows]
version = "0.61"
features = [
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_System_Variant"
]